runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /css
  static_dir: css

- url: /js
  static_dir: js

- url: /_ah/api/.*
  script: tasktimer_api.app
  secure: always

- url: /.*
  script: app.app
  secure: always

builtins:
- remote_api: on

inbound_services:
- warmup

libraries:
- name: jinja2
  version: '2.6'
- name: pycrypto
  version: 2.6
- name: ssl
  version: 2.7.11
